services:
  - type: web
    name: tranx-api
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn tranx.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
